# Generated by Django 4.1.3 on 2022-12-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_someone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=120)),
            ],
        ),
    ]
