# Generated by Django 4.1.3 on 2022-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PostIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='from_someone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
