# Generated by Django 4.1.3 on 2022-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PostIt', '0003_alter_post_from_someone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='from_someone',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
