# Generated by Django 4.1.3 on 2022-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PostIt', '0007_alter_post_from_someone_alter_post_to_someone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(max_length=120),
        ),
    ]
