# Generated by Django 4.1.3 on 2022-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cafe', '0002_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='displayname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
